// Quiz do dia — futebol brasileiro (clubes). { id, q, a: [CORRETA, errada, errada, errada] }.
// Só fatos certos e estáveis (títulos até 2024, apelidos, clássicos, estádios, ídolos).
export const BRASIL = [
  { id: 'b01', q: 'Qual é o maior campeão do Campeonato Brasileiro?', a: ['Palmeiras', 'Flamengo', 'Santos', 'Corinthians'] },
  { id: 'b02', q: 'Qual clube foi campeão brasileiro de 2024?', a: ['Botafogo', 'Palmeiras', 'Flamengo', 'Fortaleza'] },
  { id: 'b03', q: 'Quem venceu a Libertadores de 2024, na final contra o Atlético-MG?', a: ['Botafogo', 'Flamengo', 'River Plate', 'Palmeiras'] },
  { id: 'b04', q: 'Quem venceu a Libertadores de 2023, na final contra o Boca Juniors?', a: ['Fluminense', 'Palmeiras', 'Internacional', 'Flamengo'] },
  { id: 'b05', q: 'Quem venceu a Libertadores de 2022, na final contra o Athletico-PR?', a: ['Flamengo', 'Palmeiras', 'Corinthians', 'São Paulo'] },
  { id: 'b06', q: 'Contra quem o Palmeiras ganhou a final da Libertadores de 2021?', a: ['Flamengo', 'Atlético-MG', 'Santos', 'Boca Juniors'] },
  { id: 'b07', q: 'Contra quem o Palmeiras ganhou a final da Libertadores de 2020, no Maracanã?', a: ['Santos', 'Flamengo', 'Grêmio', 'River Plate'] },
  { id: 'b08', q: 'Contra quem o Flamengo virou a final da Libertadores de 2019, em Lima?', a: ['River Plate', 'Boca Juniors', 'Grêmio', 'Independiente del Valle'] },
  { id: 'b09', q: 'Quem fez os dois gols da virada do Flamengo na final da Libertadores de 2019?', a: ['Gabigol', 'Bruno Henrique', 'Arrascaeta', 'Everton Ribeiro'] },
  { id: 'b10', q: 'Qual foi o primeiro clube brasileiro campeão da Libertadores, em 1962?', a: ['Santos', 'Cruzeiro', 'Palmeiras', 'São Paulo'] },
  { id: 'b11', q: 'Qual clube brasileiro venceu o Chelsea na final do Mundial de Clubes de 2012?', a: ['Corinthians', 'Santos', 'Internacional', 'São Paulo'] },
  { id: 'b12', q: 'Quem fez o gol do título do Corinthians no Mundial de 2012?', a: ['Paolo Guerrero', 'Emerson Sheik', 'Danilo', 'Jorge Henrique'] },
  { id: 'b13', q: 'Qual clube o São Paulo venceu na final do Mundial de Clubes de 2005?', a: ['Liverpool', 'Barcelona', 'Chelsea', 'Milan'] },
  { id: 'b14', q: 'Qual clube o Internacional venceu na final do Mundial de Clubes de 2006?', a: ['Barcelona', 'Milan', 'Liverpool', 'Real Madrid'] },
  { id: 'b15', q: 'Qual clube o Flamengo de Zico goleou por 3 x 0 no Mundial de 1981?', a: ['Liverpool', 'Aston Villa', 'Nottingham Forest', 'Juventus'] },
  { id: 'b16', q: 'Qual é o maior estádio do Brasil em capacidade?', a: ['Maracanã', 'Mané Garrincha', 'Morumbi', 'Mineirão'] },
  { id: 'b17', q: 'Qual é o estádio do Palmeiras?', a: ['Allianz Parque', 'Neo Química Arena', 'Morumbi', 'Canindé'] },
  { id: 'b18', q: 'Qual é o estádio do Corinthians?', a: ['Neo Química Arena', 'Allianz Parque', 'Pacaembu', 'Morumbi'] },
  { id: 'b19', q: 'De qual clube é o apelido "Timão"?', a: ['Corinthians', 'Palmeiras', 'São Paulo', 'Santos'] },
  { id: 'b20', q: 'De qual clube é o apelido "Peixe"?', a: ['Santos', 'Vasco', 'Náutico', 'Sport'] },
  { id: 'b21', q: 'O porco é mascote de qual clube?', a: ['Palmeiras', 'Corinthians', 'Santos', 'Coritiba'] },
  { id: 'b22', q: 'O urubu é mascote de qual clube?', a: ['Flamengo', 'Vasco', 'Botafogo', 'Fluminense'] },
  { id: 'b23', q: 'Qual clube é chamado de "Galo"?', a: ['Atlético Mineiro', 'Cruzeiro', 'América-MG', 'Athletico Paranaense'] },
  { id: 'b24', q: 'A raposa é mascote de qual clube?', a: ['Cruzeiro', 'Atlético Mineiro', 'Grêmio', 'Internacional'] },
  { id: 'b25', q: 'Qual clube é o "Imortal Tricolor"?', a: ['Grêmio', 'Internacional', 'Fluminense', 'São Paulo'] },
  { id: 'b26', q: 'Qual clube é chamado de "Colorado"?', a: ['Internacional', 'Grêmio', 'Juventude', 'Criciúma'] },
  { id: 'b27', q: 'Qual clube é o "Leão da Ilha"?', a: ['Sport', 'Santa Cruz', 'Náutico', 'Ceará'] },
  { id: 'b28', q: 'Qual clube tem o apelido de "Timbu"?', a: ['Náutico', 'Santa Cruz', 'Sport', 'Retrô'] },
  { id: 'b29', q: 'Qual clube é a "Cobra Coral"?', a: ['Santa Cruz', 'Náutico', 'Sport', 'Treze'] },
  { id: 'b30', q: 'Qual clube tem o apelido de "Vozão"?', a: ['Ceará', 'Fortaleza', 'Ferroviário', 'Bahia'] },
  { id: 'b31', q: 'Qual clube é o "Papão da Curuzu"?', a: ['Paysandu', 'Remo', 'Tuna Luso', 'Castanhal'] },
  { id: 'b32', q: 'Qual clube é o "Esquadrão de Aço"?', a: ['Bahia', 'Vitória', 'Sport', 'Ceará'] },
  { id: 'b33', q: 'Qual clube de Campinas é o "Bugre"?', a: ['Guarani', 'Ponte Preta', 'Juventude', 'Criciúma'] },
  { id: 'b34', q: 'Qual clube de Campinas é a "Macaca"?', a: ['Ponte Preta', 'Guarani', 'XV de Piracicaba', 'Red Bull Bragantino'] },
  { id: 'b35', q: 'Qual clube paranaense é o "Coxa"?', a: ['Coritiba', 'Athletico Paranaense', 'Paraná Clube', 'Londrina'] },
  { id: 'b36', q: 'Qual clube paranaense é o "Furacão"?', a: ['Athletico Paranaense', 'Coritiba', 'Paraná Clube', 'Operário'] },
  { id: 'b37', q: 'Qual clube é o "Verdão do Oeste"?', a: ['Chapecoense', 'Palmeiras', 'Goiás', 'Juventude'] },
  { id: 'b38', q: 'Qual clube é o "Gigante da Colina"?', a: ['Vasco', 'Flamengo', 'Fluminense', 'Botafogo'] },
  { id: 'b39', q: 'O Fla-Flu é o clássico entre...', a: ['Flamengo e Fluminense', 'Flamengo e Vasco', 'Fluminense e Vasco', 'Flamengo e Botafogo'] },
  { id: 'b40', q: 'O Grenal é o clássico entre...', a: ['Grêmio e Internacional', 'Grêmio e Juventude', 'Internacional e Juventude', 'Grêmio e Caxias'] },
  { id: 'b41', q: 'O "Clássico dos Clássicos" de Pernambuco é entre...', a: ['Náutico e Sport', 'Sport e Santa Cruz', 'Náutico e Santa Cruz', 'Sport e Retrô'] },
  { id: 'b42', q: 'O "Clássico das Multidões" de Pernambuco é entre...', a: ['Sport e Santa Cruz', 'Náutico e Sport', 'Náutico e Santa Cruz', 'Santa Cruz e Retrô'] },
  { id: 'b43', q: 'O Clássico-Rei do Ceará é entre...', a: ['Ceará e Fortaleza', 'Ceará e Ferroviário', 'Fortaleza e Ferroviário', 'Ceará e Floresta'] },
  { id: 'b44', q: 'O Ba-Vi é o clássico entre...', a: ['Bahia e Vitória', 'Bahia e Sport', 'Vitória e Sport', 'Bahia e Ceará'] },
  { id: 'b45', q: 'O Dérbi Paulista é o clássico entre...', a: ['Corinthians e Palmeiras', 'Corinthians e São Paulo', 'Palmeiras e São Paulo', 'Santos e Corinthians'] },
  { id: 'b46', q: 'O Choque-Rei é o clássico entre...', a: ['Palmeiras e São Paulo', 'Corinthians e São Paulo', 'Palmeiras e Santos', 'São Paulo e Santos'] },
  { id: 'b47', q: 'O Majestoso é o clássico entre...', a: ['Corinthians e São Paulo', 'Palmeiras e São Paulo', 'Corinthians e Santos', 'São Paulo e Santos'] },
  { id: 'b48', q: 'O Re-Pa é o clássico entre...', a: ['Remo e Paysandu', 'Remo e Tuna Luso', 'Paysandu e Tuna Luso', 'Remo e Sampaio Corrêa'] },
  { id: 'b49', q: 'Em que ano o Brasileirão passou a ser disputado em pontos corridos?', a: ['2003', '1999', '2001', '2006'] },
  { id: 'b50', q: 'Qual foi o primeiro campeão brasileiro por pontos corridos, em 2003?', a: ['Cruzeiro', 'Santos', 'São Paulo', 'Athletico Paranaense'] },
  { id: 'b51', q: 'Qual clube foi tricampeão brasileiro seguido em 2006, 2007 e 2008?', a: ['São Paulo', 'Corinthians', 'Palmeiras', 'Flamengo'] },
  { id: 'b52', q: 'Em qual clube Neymar começou a carreira profissional?', a: ['Santos', 'São Paulo', 'Palmeiras', 'Corinthians'] },
  { id: 'b53', q: 'Zico é o maior ídolo da história de qual clube?', a: ['Flamengo', 'Vasco', 'Fluminense', 'Botafogo'] },
  { id: 'b54', q: 'Roberto Dinamite é o maior artilheiro da história de qual clube?', a: ['Vasco', 'Flamengo', 'Botafogo', 'Fluminense'] },
  { id: 'b55', q: 'Qual goleiro, ídolo do São Paulo, é o que mais fez gols na história?', a: ['Rogério Ceni', 'José Luis Chilavert', 'Marcos', 'Dida'] },
  { id: 'b56', q: 'O goleiro Marcos, o "São Marcos", é ídolo de qual clube?', a: ['Palmeiras', 'Corinthians', 'São Paulo', 'Santos'] },
  { id: 'b57', q: 'Por qual clube Garrincha jogou a maior parte da carreira?', a: ['Botafogo', 'Flamengo', 'Corinthians', 'Fluminense'] },
  { id: 'b58', q: 'Qual clube foi campeão brasileiro de 2021, depois de 50 anos sem o título?', a: ['Atlético Mineiro', 'Flamengo', 'Palmeiras', 'Fortaleza'] },
  { id: 'b59', q: 'Qual técnico português levou o Flamengo aos títulos da Libertadores e do Brasileirão em 2019?', a: ['Jorge Jesus', 'Abel Ferreira', 'Vítor Pereira', 'Paulo Sousa'] },
  { id: 'b60', q: 'Qual técnico português ganhou duas Libertadores seguidas com o Palmeiras (2020 e 2021)?', a: ['Abel Ferreira', 'Jorge Jesus', 'Vítor Pereira', 'Luís Castro'] },
  { id: 'b61', q: 'Em qual cidade fica o estádio Mané Garrincha?', a: ['Brasília', 'Rio de Janeiro', 'Goiânia', 'Belo Horizonte'] },
  { id: 'b62', q: 'Em qual cidade fica o Mineirão?', a: ['Belo Horizonte', 'Uberlândia', 'Juiz de Fora', 'Contagem'] },
  { id: 'b63', q: 'O Beira-Rio é o estádio de qual clube?', a: ['Internacional', 'Grêmio', 'Juventude', 'Caxias'] },
  { id: 'b64', q: 'A Ilha do Retiro é o estádio de qual clube?', a: ['Sport', 'Náutico', 'Santa Cruz', 'Retrô'] },
  { id: 'b65', q: 'O Arruda é o estádio de qual clube?', a: ['Santa Cruz', 'Sport', 'Náutico', 'Central'] },
  { id: 'b66', q: 'Os Aflitos são o estádio de qual clube?', a: ['Náutico', 'Santa Cruz', 'Sport', 'Salgueiro'] },
  { id: 'b67', q: 'São Januário é o estádio de qual clube?', a: ['Vasco', 'Flamengo', 'Fluminense', 'Botafogo'] },
  { id: 'b68', q: 'A Vila Belmiro é o estádio de qual clube?', a: ['Santos', 'Palmeiras', 'São Paulo', 'Portuguesa'] },
  { id: 'b69', q: 'O Morumbi é o estádio de qual clube?', a: ['São Paulo', 'Corinthians', 'Palmeiras', 'Santos'] },
  { id: 'b70', q: 'A Arena da Baixada é o estádio de qual clube?', a: ['Athletico Paranaense', 'Coritiba', 'Paraná Clube', 'Londrina'] },
];
