// Quiz do dia — futebol mundial. { id, q, a: [CORRETA, errada, errada, errada] } — o servidor
// embaralha as alternativas por jogador. Base: quiz da Brasil Paralelo (13/09/2026; ficaram de
// fora as 2 perguntas com resposta errada lá) + perguntas nossas. Só fatos certos e estáveis.
export const MUNDO = [
  { id: 'm01', q: 'Quem ganhou a Bola de Ouro de 2012?', a: ['Lionel Messi', 'Cristiano Ronaldo', 'Andrés Iniesta', 'Xavi'] },
  { id: 'm02', q: 'Qual é a competição de seleções mais importante do mundo?', a: ['Copa do Mundo', 'Copa América', 'Eurocopa', 'Copa das Confederações'] },
  { id: 'm03', q: 'Qual clube venceu a Liga dos Campeões da UEFA de 2022?', a: ['Real Madrid', 'Liverpool', 'Bayern de Munique', 'Chelsea'] },
  { id: 'm04', q: 'Quantas Bolas de Ouro Lionel Messi tinha conquistado até 2023?', a: ['8', '5', '6', '7'] },
  { id: 'm05', q: 'Qual seleção venceu a Copa do Mundo de 2018?', a: ['França', 'Croácia', 'Alemanha', 'Bélgica'] },
  { id: 'm06', q: 'Qual clube tem mais títulos da Liga dos Campeões da UEFA?', a: ['Real Madrid', 'Milan', 'Bayern de Munique', 'Liverpool'] },
  { id: 'm07', q: 'Qual jogador é conhecido como "CR7"?', a: ['Cristiano Ronaldo', 'Neymar', 'Kylian Mbappé', 'Ronaldinho'] },
  { id: 'm08', q: 'Em que ano foi disputada a primeira Copa do Mundo?', a: ['1930', '1924', '1934', '1950'] },
  { id: 'm09', q: 'Quem foi o primeiro vencedor da Bola de Ouro, em 1956?', a: ['Stanley Matthews', 'Alfredo Di Stéfano', 'Raymond Kopa', 'Johan Cruyff'] },
  { id: 'm10', q: 'Qual país sediou a Copa do Mundo de 2014?', a: ['Brasil', 'África do Sul', 'Alemanha', 'Rússia'] },
  { id: 'm11', q: 'Quem é o maior artilheiro da história da Liga dos Campeões da UEFA?', a: ['Cristiano Ronaldo', 'Lionel Messi', 'Robert Lewandowski', 'Raúl'] },
  { id: 'm12', q: 'Quantas seleções disputaram cada Copa do Mundo de 1998 a 2022?', a: ['32', '24', '36', '48'] },
  { id: 'm13', q: 'Desde que virou "Liga dos Campeões" (1992), qual clube foi o único tricampeão seguido?', a: ['Real Madrid', 'Barcelona', 'Bayern de Munique', 'Milan'] },
  { id: 'm14', q: 'Quem ganhou a Bola de Ouro de 2018?', a: ['Luka Modrić', 'Cristiano Ronaldo', 'Lionel Messi', 'Antoine Griezmann'] },
  { id: 'm15', q: 'Qual seleção venceu a primeira Copa do Mundo, em 1930?', a: ['Uruguai', 'Argentina', 'Brasil', 'Itália'] },
  { id: 'm16', q: 'Quantos gols Pelé marcou em Copas do Mundo?', a: ['12', '10', '14', '15'] },
  { id: 'm17', q: 'Quem ganhou mais Bolas de Ouro na década de 2010?', a: ['Lionel Messi', 'Cristiano Ronaldo', 'Luka Modrić', 'Andrés Iniesta'] },
  { id: 'm18', q: 'Qual clube virou nos acréscimos a final da Liga dos Campeões de 1999 contra o Bayern?', a: ['Manchester United', 'Juventus', 'Barcelona', 'Real Madrid'] },
  { id: 'm19', q: 'Quem foi o artilheiro da Copa do Mundo de 2014?', a: ['James Rodríguez', 'Thomas Müller', 'Neymar', 'Lionel Messi'] },
  { id: 'm20', q: 'Qual seleção tem mais títulos de Copa do Mundo?', a: ['Brasil', 'Alemanha', 'Itália', 'Argentina'] },
  { id: 'm21', q: 'Qual zagueiro ganhou a Bola de Ouro de 2006?', a: ['Fabio Cannavaro', 'Alessandro Nesta', 'John Terry', 'Lúcio'] },
  { id: 'm22', q: 'Qual foi o primeiro clube inglês campeão europeu, em 1968?', a: ['Manchester United', 'Liverpool', 'Nottingham Forest', 'Aston Villa'] },
  { id: 'm23', q: 'Quantas Copas do Mundo a Itália já ganhou?', a: ['4', '2', '3', '5'] },
  { id: 'm24', q: 'Qual foi o placar do "Maracanaço", o jogo decisivo da Copa de 1950?', a: ['Uruguai 2 x 1 Brasil', 'Brasil 2 x 1 Uruguai', 'Uruguai 1 x 0 Brasil', 'Uruguai 3 x 2 Brasil'] },
  { id: 'm25', q: 'Quem é o jogador mais jovem a ganhar a Bola de Ouro?', a: ['Ronaldo Fenômeno', 'Michael Owen', 'George Best', 'Lionel Messi'] },
  { id: 'm26', q: 'Qual clube venceu a primeira Copa dos Campeões Europeus, em 1956?', a: ['Real Madrid', 'Benfica', 'Milan', 'Stade de Reims'] },
  { id: 'm27', q: 'Quem foi o primeiro jogador de fora da Europa a ganhar a Bola de Ouro, em 1995?', a: ['George Weah', 'Ronaldo Fenômeno', 'Romário', "Samuel Eto'o"] },
  { id: 'm28', q: 'Qual seleção venceu a Copa do Mundo de 2022?', a: ['Argentina', 'França', 'Croácia', 'Marrocos'] },
  { id: 'm29', q: 'Qual país sediou a Copa do Mundo de 2022?', a: ['Catar', 'Emirados Árabes', 'Arábia Saudita', 'Rússia'] },
  { id: 'm30', q: 'Contra quem a Espanha ganhou a final da Copa de 2010?', a: ['Holanda', 'Alemanha', 'Uruguai', 'Paraguai'] },
  { id: 'm31', q: 'Quem fez o gol do título da Espanha na Copa de 2010?', a: ['Andrés Iniesta', 'David Villa', 'Xavi', 'Fernando Torres'] },
  { id: 'm32', q: 'Quem é o maior artilheiro da história das Copas do Mundo, com 16 gols?', a: ['Miroslav Klose', 'Ronaldo Fenômeno', 'Gerd Müller', 'Just Fontaine'] },
  { id: 'm33', q: 'Quantos gols Just Fontaine marcou na Copa de 1958, recorde em uma única Copa?', a: ['13', '9', '11', '15'] },
  { id: 'm34', q: 'Qual seleção venceu a Copa do Mundo de 2006?', a: ['Itália', 'França', 'Alemanha', 'Portugal'] },
  { id: 'm35', q: 'Em quem Zidane deu a cabeçada na final da Copa de 2006?', a: ['Marco Materazzi', 'Fabio Cannavaro', 'Gennaro Gattuso', 'Andrea Pirlo'] },
  { id: 'm36', q: 'Quem fez o gol de mão conhecido como "La Mano de Dios", em 1986?', a: ['Diego Maradona', 'Mario Kempes', 'Gabriel Batistuta', 'Jorge Valdano'] },
  { id: 'm37', q: 'Contra qual seleção foi o gol "La Mano de Dios"?', a: ['Inglaterra', 'Alemanha Ocidental', 'Bélgica', 'Itália'] },
  { id: 'm38', q: 'Qual seleção venceu a Eurocopa de 2016?', a: ['Portugal', 'França', 'Alemanha', 'País de Gales'] },
  { id: 'm39', q: 'Qual seleção venceu a Eurocopa de 2024?', a: ['Espanha', 'Inglaterra', 'França', 'Holanda'] },
  { id: 'm40', q: 'Qual seleção venceu a Copa América de 2021, no Maracanã?', a: ['Argentina', 'Brasil', 'Uruguai', 'Colômbia'] },
  { id: 'm41', q: 'Qual clube venceu a Liga dos Campeões de 2023, contra a Inter de Milão?', a: ['Manchester City', 'Real Madrid', 'Bayern de Munique', 'Milan'] },
  { id: 'm42', q: 'Contra quem o Real Madrid ganhou a final da Liga dos Campeões de 2024?', a: ['Borussia Dortmund', 'Manchester City', 'Bayern de Munique', 'Inter de Milão'] },
  { id: 'm43', q: 'Quem era o técnico do Barcelona do "tiki-taka" de 2008 a 2012?', a: ['Pep Guardiola', 'Frank Rijkaard', 'Luis Enrique', 'Tito Vilanova'] },
  { id: 'm44', q: 'Como se chama o estádio do Barcelona?', a: ['Camp Nou', 'Santiago Bernabéu', 'Mestalla', 'San Mamés'] },
  { id: 'm45', q: 'Como se chama o estádio do Real Madrid?', a: ['Santiago Bernabéu', 'Camp Nou', 'Metropolitano', 'San Siro'] },
  { id: 'm46', q: 'Qual clube inglês tem o apelido de "Red Devils"?', a: ['Manchester United', 'Liverpool', 'Arsenal', 'Nottingham Forest'] },
  { id: 'm47', q: 'Qual clube foi campeão inglês invicto na temporada 2003/04, os "Invencíveis"?', a: ['Arsenal', 'Chelsea', 'Manchester United', 'Liverpool'] },
  { id: 'm48', q: 'Quais países sediaram juntos a Copa do Mundo de 2002?', a: ['Coreia do Sul e Japão', 'China e Japão', 'Coreia do Sul e China', 'Japão e Tailândia'] },
  { id: 'm49', q: 'Quais países sediam a Copa do Mundo de 2026?', a: ['Estados Unidos, Canadá e México', 'Estados Unidos e México', 'Estados Unidos e Canadá', 'Só os Estados Unidos'] },
  { id: 'm50', q: 'Quantas seleções disputam a Copa do Mundo de 2026?', a: ['48', '32', '40', '64'] },
  { id: 'm51', q: 'Quem era o craque do "Carrossel Holandês" na Copa de 1974?', a: ['Johan Cruyff', 'Marco van Basten', 'Ruud Gullit', 'Dennis Bergkamp'] },
  { id: 'm52', q: 'Qual lenda alemã tinha o apelido de "Kaiser"?', a: ['Franz Beckenbauer', 'Gerd Müller', 'Lothar Matthäus', 'Karl-Heinz Rummenigge'] },
  { id: 'm53', q: 'Qual brasileiro ganhou a Bola de Ouro de 2007?', a: ['Kaká', 'Ronaldinho', 'Ronaldo Fenômeno', 'Robinho'] },
  { id: 'm54', q: 'Quem ganhou a Bola de Ouro de 2005?', a: ['Ronaldinho', 'Frank Lampard', 'Steven Gerrard', 'Thierry Henry'] },
  { id: 'm55', q: 'Quem ganhou a Bola de Ouro de 2022?', a: ['Karim Benzema', 'Sadio Mané', 'Kevin De Bruyne', 'Robert Lewandowski'] },
  { id: 'm56', q: 'Quem ganhou a Bola de Ouro de 2024?', a: ['Rodri', 'Vinícius Júnior', 'Jude Bellingham', 'Dani Carvajal'] },
  { id: 'm57', q: 'Quem ganhou a Bola de Ouro de 2002, ano do Penta?', a: ['Ronaldo Fenômeno', 'Roberto Carlos', 'Oliver Kahn', 'Zinedine Zidane'] },
  { id: 'm58', q: 'Por qual clube Lionel Messi jogou mais tempo na carreira?', a: ['Barcelona', 'Paris Saint-Germain', 'Inter Miami', "Newell's Old Boys"] },
  { id: 'm59', q: 'Qual seleção venceu a Copa América de 2024, nos Estados Unidos?', a: ['Argentina', 'Colômbia', 'Uruguai', 'Brasil'] },
  { id: 'm60', q: 'Qual clube inglês é conhecido como "The Reds" e canta "You\'ll Never Walk Alone"?', a: ['Liverpool', 'Manchester United', 'Arsenal', 'Nottingham Forest'] },
];
