// Quiz do dia — Seleção Brasileira e Copas. { id, q, a: [CORRETA, errada, errada, errada] }.
export const SELECAO = [
  { id: 's01', q: 'Quantas Copas do Mundo o Brasil já ganhou?', a: ['5', '4', '6', '3'] },
  { id: 's02', q: 'Em que país o Brasil ganhou sua primeira Copa, em 1958?', a: ['Suécia', 'Chile', 'Suíça', 'Inglaterra'] },
  { id: 's03', q: 'Em que país o Brasil foi bicampeão mundial, em 1962?', a: ['Chile', 'Suécia', 'México', 'Inglaterra'] },
  { id: 's04', q: 'Em que país o Brasil foi tricampeão mundial, em 1970?', a: ['México', 'Chile', 'Alemanha Ocidental', 'Argentina'] },
  { id: 's05', q: 'Em que país o Brasil foi tetracampeão mundial, em 1994?', a: ['Estados Unidos', 'Itália', 'França', 'México'] },
  { id: 's06', q: 'Contra quem o Brasil decidiu nos pênaltis a final da Copa de 1994?', a: ['Itália', 'Suécia', 'Holanda', 'Alemanha'] },
  { id: 's07', q: 'Qual italiano mandou por cima o último pênalti da final de 1994?', a: ['Roberto Baggio', 'Paolo Maldini', 'Alessandro Del Piero', 'Gianluca Pagliuca'] },
  { id: 's08', q: 'Contra quem o Brasil ganhou a final da Copa de 2002?', a: ['Alemanha', 'Turquia', 'Coreia do Sul', 'Argentina'] },
  { id: 's09', q: 'Quem fez os dois gols do Brasil na final da Copa de 2002?', a: ['Ronaldo Fenômeno', 'Rivaldo', 'Ronaldinho', 'Kléberson'] },
  { id: 's10', q: 'Quem levantou a taça como capitão do Brasil em 2002?', a: ['Cafu', 'Roberto Carlos', 'Rivaldo', 'Ronaldo Fenômeno'] },
  { id: 's11', q: 'Quem levantou a taça como capitão do Brasil em 1994?', a: ['Dunga', 'Taffarel', 'Bebeto', 'Romário'] },
  { id: 's12', q: 'Quem era o capitão do Brasil na Copa de 1970?', a: ['Carlos Alberto Torres', 'Pelé', 'Gérson', 'Rivellino'] },
  { id: 's13', q: 'Quem foi campeão do mundo como jogador (1958 e 1962) e como técnico (1970)?', a: ['Zagallo', 'Didi', 'Vicente Feola', 'Aymoré Moreira'] },
  { id: 's14', q: 'Quem era o técnico do Brasil no Penta, em 2002?', a: ['Luiz Felipe Scolari', 'Carlos Alberto Parreira', 'Vanderlei Luxemburgo', 'Emerson Leão'] },
  { id: 's15', q: 'Quem era o técnico do Brasil no Tetra, em 1994?', a: ['Carlos Alberto Parreira', 'Luiz Felipe Scolari', 'Telê Santana', 'Zagallo'] },
  { id: 's16', q: 'Contra quem o Brasil perdeu por 7 x 1 na Copa de 2014?', a: ['Alemanha', 'Holanda', 'Argentina', 'Espanha'] },
  { id: 's17', q: 'Em qual estádio foi o 7 x 1 da Copa de 2014?', a: ['Mineirão', 'Maracanã', 'Neo Química Arena', 'Mané Garrincha'] },
  { id: 's18', q: 'Com quantos anos Pelé foi campeão do mundo pela primeira vez, em 1958?', a: ['17', '16', '18', '19'] },
  { id: 's19', q: 'Quantas Copas do Mundo Pelé ganhou como jogador?', a: ['3', '2', '4', '5'] },
  { id: 's20', q: 'Quantos gols Ronaldo Fenômeno marcou em Copas do Mundo?', a: ['15', '12', '14', '16'] },
  { id: 's21', q: 'Quem foi o artilheiro da Copa do Mundo de 2002?', a: ['Ronaldo Fenômeno', 'Rivaldo', 'Miroslav Klose', 'Christian Vieri'] },
  { id: 's22', q: 'Em que ano o Brasil conquistou o Penta?', a: ['2002', '1998', '2006', '1994'] },
  { id: 's23', q: 'Quem é o maior artilheiro da história da Seleção Brasileira?', a: ['Neymar', 'Pelé', 'Ronaldo Fenômeno', 'Romário'] },
  { id: 's24', q: 'Qual seleção o Brasil venceu na final da Copa América de 2019, no Maracanã?', a: ['Peru', 'Argentina', 'Chile', 'Uruguai'] },
  { id: 's25', q: 'Em que Olimpíada o futebol masculino do Brasil ganhou seu primeiro ouro?', a: ['Rio 2016', 'Londres 2012', 'Pequim 2008', 'Atlanta 1996'] },
  { id: 's26', q: 'Contra quem o Brasil ganhou nos pênaltis o ouro olímpico de 2016?', a: ['Alemanha', 'Argentina', 'México', 'Espanha'] },
  { id: 's27', q: 'Contra quem o Brasil ganhou o ouro olímpico de Tóquio?', a: ['Espanha', 'Alemanha', 'México', 'Japão'] },
  { id: 's28', q: 'Quem foi eleito o melhor jogador do mundo pela FIFA em 1994?', a: ['Romário', 'Bebeto', 'Roberto Baggio', 'Hristo Stoichkov'] },
  { id: 's29', q: 'Em que ano o Brasil sediou uma Copa do Mundo pela primeira vez?', a: ['1950', '1938', '1962', '1974'] },
  { id: 's30', q: 'Qual é a única seleção que disputou todas as Copas do Mundo?', a: ['Brasil', 'Alemanha', 'Itália', 'Argentina'] },
  { id: 's31', q: 'Com Pelé machucado, quem foi o grande craque do Brasil na Copa de 1962?', a: ['Garrincha', 'Zito', 'Djalma Santos', 'Nílton Santos'] },
  { id: 's32', q: 'Contra quem o Brasil ganhou a final da Copa de 1970?', a: ['Itália', 'Uruguai', 'Inglaterra', 'Alemanha Ocidental'] },
  { id: 's33', q: 'Contra quem o Brasil ganhou a final da Copa de 1958?', a: ['Suécia', 'França', 'País de Gales', 'Alemanha Ocidental'] },
  { id: 's34', q: 'Contra quem o Brasil ganhou a final da Copa de 1962?', a: ['Tchecoslováquia', 'Iugoslávia', 'Hungria', 'Chile'] },
  { id: 's35', q: 'Para quem o Brasil perdeu a final da Copa de 1998?', a: ['França', 'Holanda', 'Itália', 'Croácia'] },
  { id: 's36', q: 'Quem eliminou o Brasil nos pênaltis nas quartas da Copa de 2022?', a: ['Croácia', 'Argentina', 'Marrocos', 'França'] },
  { id: 's37', q: 'Quem eliminou o Brasil nas quartas da Copa de 2018?', a: ['Bélgica', 'França', 'Croácia', 'Suíça'] },
  { id: 's38', q: 'Quem eliminou o Brasil nas quartas da Copa de 2010?', a: ['Holanda', 'Paraguai', 'Gana', 'Portugal'] },
  { id: 's39', q: 'Quem eliminou o Brasil nas quartas da Copa de 2006?', a: ['França', 'Portugal', 'Itália', 'Alemanha'] },
  { id: 's40', q: 'Quem era o técnico do Brasil na Copa de 2022?', a: ['Tite', 'Dunga', 'Mano Menezes', 'Fernando Diniz'] },
  { id: 's41', q: 'Qual técnico italiano assumiu a Seleção Brasileira em 2025?', a: ['Carlo Ancelotti', 'Roberto Mancini', 'Fabio Capello', 'Marcello Lippi'] },
  { id: 's42', q: 'Quem era o capitão do Brasil que ergueu a taça em 1958?', a: ['Bellini', 'Didi', 'Nílton Santos', 'Zagallo'] },
];
